# Generated by Django 5.0.6 on 2024-07-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewUser',
        ),
    ]
