# Generated by Django 5.0.6 on 2024-07-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_rename_user_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='User',
        ),
    ]
